# Generated by Django 4.2.2 on 2023-06-23 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, to='materials.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=models.TextField(default='gray'),
        ),
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=models.TextField(default='white'),
        ),
        migrations.AlterField(
            model_name='material',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='material',
            name='date_edited',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_edited',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='materials',
            field=models.ManyToManyField(blank=True, to='materials.material'),
        ),
    ]
