# Generated by Django 4.2.2 on 2023-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='gray', max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text_color',
            field=models.CharField(default='white', max_length=30),
        ),
    ]
